import fs from "node:fs";
import path from "node:path";
import { ALL_FORMATS, BufferSource, Input } from "mediabunny";
import sharp from "sharp";
import { describe, expect, it } from "vitest";
import { schedule } from "../src/motion";
import { BUILTIN_TEMPLATES, buildTemplatePreviewDoc } from "../src/templates";

// Generated by `npm run template-previews` (F07) and committed.
const TEMPLATES_DIR = path.resolve(__dirname, "../public/templates");
const PREVIEW_FPS = 24;
const MAX_WEBM_BYTES = 450 * 1024;
const MIN_POSTER_BYTES = 15 * 1024;
const MIN_POSTER_STDDEV = 10;

/** Standard deviation of every R, G and B value: near 0 for a flat placeholder card. */
async function pixelStdDev(file: string): Promise<number> {
  const { data } = await sharp(file).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  let sum = 0;
  for (const value of data) sum += value;
  const mean = sum / data.length;
  let variance = 0;
  for (const value of data) variance += (value - mean) ** 2;
  return Math.sqrt(variance / data.length);
}

describe("F07: template previews", () => {
  it("covers all 4 built-in templates", () => {
    expect(BUILTIN_TEMPLATES).toHaveLength(4);
  });

  it("ships no preview for a template that is not built in", () => {
    const expected = BUILTIN_TEMPLATES.flatMap((t) => [`${t.id}.webm`, `${t.id}.webp`]);
    expect(fs.readdirSync(TEMPLATES_DIR).sort()).toEqual(expected.sort());
  });

  for (const template of BUILTIN_TEMPLATES) {
    describe(template.id, () => {
      it("has a WebM preview that matches the preview document", async () => {
        const file = path.join(TEMPLATES_DIR, `${template.id}.webm`);
        expect(fs.existsSync(file), `${file} is missing`).toBe(true);
        const bytes = fs.readFileSync(file);
        expect(bytes.byteLength).toBeLessThanOrEqual(MAX_WEBM_BYTES);

        const input = new Input({ source: new BufferSource(bytes), formats: ALL_FORMATS });
        const track = await input.getPrimaryVideoTrack();
        expect(track, "no video track").not.toBeNull();

        const doc = buildTemplatePreviewDoc(template);
        const portrait = doc.aspect === "9:16";
        expect({ width: track!.displayWidth, height: track!.displayHeight }).toEqual(
          portrait ? { width: 360, height: 640 } : { width: 640, height: 360 },
        );

        const duration = await input.computeDuration();
        const { total } = schedule(doc);
        expect(Math.abs(duration - total)).toBeLessThanOrEqual(1 / PREVIEW_FPS + 1e-6);
      });

      it("has a WebP poster with real image content", async () => {
        const file = path.join(TEMPLATES_DIR, `${template.id}.webp`);
        expect(fs.existsSync(file), `${file} is missing`).toBe(true);
        expect(fs.statSync(file).size).toBeGreaterThanOrEqual(MIN_POSTER_BYTES);
        const meta = await sharp(file).metadata();
        expect(meta.format).toBe("webp");
        expect(await pixelStdDev(file)).toBeGreaterThan(MIN_POSTER_STDDEV);
      });
    });
  }
});
